#!/usr/bin/env python
""" This script creates the image of a virtual machine that can be published 
online.
"""

# standard library
import os
import sys
import glob

# Start with a clean slate
os.system('./clean --all')

# Start UBUNTU box and provision additional software
os.system('vagrant up')

# Create a new base box for publication
os.system('vagrant package --output robustToolbox.box')

# Cleanup, but keep box
os.system('./clean')
