#!/usr/bin/env python
""" Script to compare the RESTUD program with the ROBUPY package.
"""

# standard library
from datetime import timedelta
from datetime import datetime

import numpy as np

import argparse
import logging
import random
import sys
import os

# project
from modules.auxiliary import compile_package, cleanup, distribute_input
from modules.auxiliary import start_logging, finish
from modules.battery import compare_implementations

# virtual environment
if not hasattr(sys, 'real_prefix'):
    raise AssertionError('Please use a virtual environment for testing')

''' Main Function.
'''


def run(hours):
    """ Run test battery.
    """

    start, timeout = datetime.now(), timedelta(hours=hours)

    # Initialize counter.
    dict_ = dict()

    dict_['RESTUD'] = dict()

    dict_['RESTUD']['success'] = 0

    dict_['RESTUD']['failure'] = 0

    # Logging.
    logger = logging.getLogger('DEV-TEST')

    msg = 'Initialization of a ' + str(hours) + ' hours testing run.'

    logger.info(msg)

    # Compile package
    compile_package('fast')

    # # Evaluation loop.
    while True:

        # Set seed.
        seed = random.randrange(1, 100000)

        np.random.seed(seed)

        try:

            compare_implementations()

            dict_['RESTUD']['success'] += 1

        except Exception:

            dict_['RESTUD']['failure'] += 1

            msg = 'Failure for test ' + 'ROBUPY' + ' with seed ' + str(seed)

            logger.info(msg)

        # Cleaning up after test
        cleanup()

        # Timeout.
        current = datetime.now()

        duration = current - start

        if timeout < duration:
            break

    # Finishing.
    return dict_


''' Execution of module as script.
'''
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Run development test '
                                                 'battery of ROBUPY package.',
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    parser.add_argument('--hours', action='store', dest='hours',
                        type=float, default=1.0, help='run time in hours')

    parser.add_argument('--notification', action='store_true',
                        dest='notification', default=False,
                        help='send notification')

    hours, notification = distribute_input(parser)

    start_logging()

    cleanup()

    dict_ = run(hours)

    finish(dict_, hours, notification)
