coverage:
  range: 50...100
  precision: 2
  round: down
  status:
    project:
      threshold: 5%
    patch:
      threshold: 5%

ignore:
  - ".tox/**/*"
  - "release.py"
  - "setup.py"
  - "respy/conftest.py"
  - "respy/tests/**/*"
