coverage:
  range: 50...100
  precision: 2
  round: down
  status:
    project:
      default:
        threshold: 5%
    patch:
      default:
        threshold: 5%

flags:
  unit_precise:
    paths:
      - .
  unit_edge_case:
    paths:
      - .
  unit_rest:
    paths:
      - .
  integration_precise:
    paths:
      - .
  integration_edge_case:
    paths:
      - .
  integration_rest:
    paths:
      - .
  end_to_end_precise:
    paths:
      - .
  end_to_end_edge_case:
    paths:
      - .
  end_to_end_rest:
    paths:
      - .

ignore:
  - ".tox/**/*"
  - "release.py"
  - "setup.py"
  - "respy/conftest.py"
  - "respy/tests/**/*"
