codecov:
  branch: main

coverage:
  precision: 2
  round: down
  range: 80...100
  status:
    project:
      default:
        threshold: 1%
      patch:
        default:
          threshold: 5%
      unit:
        flags:
          - unit
      integration:
        flags:
          - integration
      end_to_end:
        flags:
          - end_to_end

ignore:
  - ".tox/**/*"
  - "setup.py"
  - "respy/conftest.py"
  - "respy/tests/**/*"
  - "development/**/*"
  - "docs/**/*"
