#!/usr/bin/env python
""" This script cleans the COMPU directories.
"""

# standard library
import os

# module-wide variables
HOME = os.path.dirname(os.path.realpath(__file__))

# Setup
os.chdir(HOME)

# module-wide variables
DIRECTORIES = ['graphs']

# Iterate over the two directories and call the cleanup scripts
for directory in DIRECTORIES:
    os.chdir(directory), os.system('./clean'), os.chdir('../')