#!/usr/bin/env python
""" This script creates the material for the analysis of the RESTUD analysis.
"""

# standard library
import argparse
import os

# module-wide variables
HOME = os.path.dirname(os.path.realpath(__file__))

# Setup
os.chdir(HOME)

''' Auxiliary functions
'''


def _distribute_inputs(parser):
    """ Process input arguments.
    """
    # Parse arguments
    args = parser.parse_args()

    # Distribute arguments
    is_graphs = args.graphs

    # Assertions
    assert (is_graphs in [True, False])

    # Finishing.
    return is_graphs


def create_material(is_graphs):
    """ This function creates the material for the RESTUD lecture.
    """
    # Cleanup
    os.system('./clean')

    # Construct relevant directories
    directories = ['simulations']
    if is_graphs:
        directories += ['graphs']

    # Iterate over relevant directories
    for dir_ in directories:
        os.chdir(dir_), os.system('./create'), os.chdir('../')

''' Execution of module as script.
'''

if __name__ == '__main__':

    parser = argparse.ArgumentParser(
        description='Solves and simulates the RESTUD economies.',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    parser.add_argument('--graphs', action='store_true', dest='graphs',
        default=False, help='create graphs based on simulations')

    is_graphs = _distribute_inputs(parser)

    create_material(is_graphs)
