#!/usr/bin/env python

# standard library
import shutil
import os


def build(bld):

    current_directory = os.getcwd()

    path = bld.env.project_paths['ROBUPY']

    os.chdir(path + '/python/f2py')

    # Link to original library
    for dir_ in ['include', 'lib']:
        try:
            os.remove(dir_)
        except OSError:
            pass

        try:
            shutil.rmtree(dir_)
        except OSError:
            pass

        os.symlink('../../fortran/' + dir_, dir_)

    f2py_call(bld)

    os.chdir(current_directory)


''' Auxiliary functions.
'''


def f2py_call(self):
    """ Create the interface to PYTHON using f2py.
    """
    os.system(
        'f2py3 -c -m  f2py_core f2py_interface_core.f90 -Iinclude -Llib '
        '-lfort_robupy')

    os.system(
        'f2py3 -c -m  f2py_debug f2py_interface_debug.f90 -Iinclude -Llib '
        '-lfort_robupy')
