#!/usr/bin/env python
""" This script cleans the COMPU directories.
"""

# standard library
import shutil
import glob
import os

# module-wide variables
SAVE_FILES = ['clean', 'create', 'update', 'model.robupy.ini', 'acropolis.pbs']
HOME = os.path.dirname(os.path.realpath(__file__))

# Setup
os.chdir(HOME)

''' Auxiliary functions
'''


def remove(names):
    """ Remove files or directories.
    """
    if not isinstance(names, list):
        names = [names]

    for name in names:
        try:
            os.remove(name)
        except IsADirectoryError:
            shutil.rmtree(name)

''' Main 
'''


for name in glob.glob('*'):

    if name in SAVE_FILES:
        pass
    else:
        remove(name)
