#!/usr/bin/env python
""" This script updates the results from the server.
"""

# standard library
import argparse
import paramiko
import socket
import glob
import sys
import os

# Check for Python 3 and host
if not (sys.version_info[0] == 3):
    raise AssertionError('Please use Python 3')
if not socket.gethostname() == 'pontos':
    raise AssertionError('Please use @pontos as host')

# module-wide variables
CLIENT_DIR = '/home/eisenhauer/robustToolbox/package/development/analyses' \
             '/compu/graphs'
KEY_DIR = '/home/peisenha/.ssh/id_rsa'

''' Functions
'''


def get_results():
    """ Get results from server.
    """
    # Starting with clean slate
    os.system('./clean')

    # Read private keys
    key = paramiko.RSAKey.from_private_key_file(KEY_DIR)

    # Open a transport
    transport = paramiko.Transport(('acropolis.uchicago.edu', 22))
    transport.connect(username='eisenhauer', pkey=key )

    # Initialize SFTP connection
    sftp = paramiko.SFTPClient.from_transport(transport)

    # Get files
    sftp.chdir(CLIENT_DIR + '/rslts')

    # Enter results container
    os.mkdir('rslts'), os.chdir('rslts')

    # Get files
    for file_ in sftp.listdir('.'):
        sftp.get(file_, file_)

    # Finishing
    sftp.close()

    transport.close()


''' Execution of module as script.
'''
if __name__ == '__main__':

    parser = argparse.ArgumentParser(
        description='Download results from @acropolis server.',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    # Run function
    get_results()