#!/usr/bin/env python
""" Script to quickly investigate failed estimation runs.
"""
# standard library
import numpy as np
import sys
import os

# virtual environment
if not hasattr(sys, 'real_prefix'):
    raise AssertionError('Please use a virtual environment for testing')

# project library
sys.path.insert(0, os.environ['ROBUPY'])
from robupy import *

# project library
from modules.auxiliary import *
import modules.tests as lib

''' Request
'''
label, seed = 'H', 221578

''' Error Reproduction
'''
if True:

    for _ in range(10):

        test = getattr(lib,'test_' + label)

        np.random.seed(seed)

        test()

else:

    robupy_obj = read('test.robupy.ini')

    robupy_obj = solve(robupy_obj)

    simulate(robupy_obj)
