#!/usr/bin/env python

# standard library
import fnmatch
import shutil
import os

top = '.'
out = '.bld'

# Set of compiler options.
DEBUG_OPTIONS = ['-O2', '-Wall', '-Wline-truncation', '-Wcharacter-truncation']
DEBUG_OPTIONS += ['-Wsurprising', '-Waliasing', '-Wimplicit-interface']
DEBUG_OPTIONS += ['-Wunused-parameter', '-fwhole-file', '-fcheck=all']
DEBUG_OPTIONS += ['-fbacktrace', '-g', '-fmax-errors=1', '-ffpe-trap=invalid']


PRODUCTION_OPTIONS = ['-O3']


def options(opt):

    opt.load('compiler_c')

    opt.load('compiler_fc')

    opt.add_option('--debug', action='store_true', dest='is_debug',
                   default=False, help='use debug compiler options')

def configure(conf):

    # Construct environment variables
    conf.env.project_paths = dict()

    conf.env.project_paths['RESPY'] = os.getcwd()

    conf.load('compiler_fc')


def build(bld):

    is_debug = bld.options.is_debug

    # The build is currently only tested for gfortran.
    if bld.env.FC_NAME == 'GFORTRAN':
        if is_debug:
            bld.env.append_unique('FCFLAGS', DEBUG_OPTIONS)
        else:
            bld.env.append_unique('FCFLAGS', PRODUCTION_OPTIONS)
    else:
        raise AssertionError('The build is only tested for GFORTRAN at this '
                             'point.')

    # Initialize directory structure
    bld.recurse("fortran")

