#!/usr/bin/env python

# standard library
import os
import glob
import shutil
import fnmatch

top = '.'
out = '.bld'

def options(opt):

    opt.load('compiler_c')

    opt.load('compiler_fc')

def configure(conf):
    
    conf.load('compiler_fc')

    conf.env.project_paths = dict()

    conf.env.project_paths['ROBUPY'] = os.getcwd()

def build(bld):
    
    bld.recurse('fort')

