AR = ['/usr/bin/ar']
ARFLAGS = ['rcs']
BINDIR = '/usr/local/bin'
COMPILER_FORTRAN = 'gfortran'
FC = ['/usr/bin/gfortran']
FCDEFINES_ST = '-D%s'
FCFLAGS_DEBUG = ['-Werror']
FCFLAGS_fcshlib = ['-fPIC']
FCINCPATH_ST = '-I%s'
FCLIBPATH_ST = '-L%s'
FCLIB_ST = '-l%s'
FCLNK_SRC_F = []
FCLNK_TGT_F = ['-o']
FCSHLIB_MARKER = '-Wl,-Bdynamic'
FCSTLIBPATH_ST = '-L%s'
FCSTLIB_MARKER = '-Wl,-Bstatic'
FCSTLIB_ST = '-l%s'
FC_NAME = 'GFORTRAN'
FC_SRC_F = []
FC_TGT_F = ['-c', '-o']
FC_VERSION = ('5', '3', '1')
FORTRANMODFLAG = ['-J', '']
LIBDIR = '/usr/local/lib'
LINKFLAGS_fcshlib = ['-shared']
LINK_FC = ['/usr/bin/gfortran']
PREFIX = '/usr/local'
SONAME_ST = '-Wl,-h,%s'
fcshlib_PATTERN = 'lib%s.so'
fcstlib_PATTERN = 'lib%s.a'
