{% set data = load_setup_py_data() %}

package:
  name: respy
  version: {{ data.get('version') }}

source:
  # git_url is nice in that it won't capture devenv stuff.  However, it only captures
  # committed code, so pay attention.
  git_url: ../

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
  run:
    - python >=3.7
    - click
    - estimagic >=0.1.2
    - hypothesis
    - joblib
    - fastparquet
    - mkl
    - numba >=0.42
    - numpy>=1.21.0
    - pandas >=0.24
    - pytest
    - python-snappy
    - pyyaml
    - scipy
test:
  requires:
    - pytest
    - pytest-xdist
  commands:
    - pytest -n auto
  source_files:
    - respy
    - tox.ini

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  license_file: LICENSE
  summary: {{ data.get('description') }}
  dev_url: https://github.com/OpenSourceEconomics/respy
  doc_url: {{ data.get('url') }}
