{% set data = load_setup_py_data() %}

package:
  name: respy
  version: {{ data.get('version') }}

source:
  # git_url is nice in that it won't capture devenv stuff.  However, it only captures
  # committed code, so pay attention.
  git_url: ../

build:
  number: 0
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python >=3.6
    - chaospy
    - click
    - estimagic >=0.0.27
    - joblib
    - mkl
    - numba >=0.42
    - numpy
    - pandas >=0.24
    - pytest
    - pyyaml
    - scipy
test:
  commands:
    - pytest
  source_files:
    - respy
    - tox.ini

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  license_file: LICENSE
  summary: {{ data.get('description') }}
  dev_url: https://github.com/OpenSourceEconomics/respy
  doc_url: {{ data.get('url') }}
