#!/usr/bin/env python
""" This module cleans the RESTUD simulations. All files are removed unless
explicitly declared as worth saving.
"""

# standard library
import shutil
import glob
import sys
import os


# module-wide variables
ESTIMATORS = ['dp3asim', 'robupy']
SPECIFICATIONS = ['data_one', 'data_two', 'data_three']

#
SAVE_FILES = ['create', 'dp3asim.f95']
SAVE_FILES += ['model.robupy.ini', 'in.txt']

def remove(names):
    """ Remove files or directories.
    """
    if not isinstance(names, list):
        names = [names]


    for name in names:

        try:
            os.remove(name)
        except IsADirectoryError:
            shutil.rmtree(name)




for estimator in ESTIMATORS:

    os.chdir(estimator)


    for name in glob.glob('*'):

        if name in SAVE_FILES + SPECIFICATIONS:
            pass
        else:
            remove(name)


    for spec in SPECIFICATIONS:

        os.chdir(spec)


        for name in glob.glob('*'):

            if name in SAVE_FILES + SPECIFICATIONS:
                pass
            else:
                remove(name)

        os.chdir('../')

    os.chdir('../')