#!/usr/bin/env python
""" This scripts starts the reproduction of the simulated samples from the
original paper using the RESTUD program and the ROBUPY package.
"""

# standard library
import os

# module-wide variables
HOME = os.path.dirname(os.path.realpath(__file__))
DIRECTORIES = ['dp3asim', 'robupy']

# Setup
os.chdir(HOME)

# Iterate over directories
for directory in DIRECTORIES:
    os.chdir(directory), os.system('./create'), os.chdir('../')